name: Publish

on:
  push:
    tags: [ v** ]
jobs:
  publish:
    name: Publish for ${{ matrix.name }}
    runs-on: ubuntu-18.04
    strategy:
        matrix:
          name: [leo_bot, leo_website]
          include:
            - name: leo_bot
              artifact_name: target/release/leo_bot
              asset_name: leo_bot-linux
            - name: leo_website
              artifact_name: target/release/leo_website
              asset_name: leo_website-linux
          
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build
        run: cargo build --release
      - name: Create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.name }}-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            /home/runner/work/esilv_bot/esilv_bot/${{ matrix.name }}-linux
